spring:
  datasource:
    url: jdbc:mysql://database:3306/examenfinal?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: root
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      dialect: org.hibernate.dialect.MySQLDialect5

eureka:    
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

server:
  port: 8081
  
management:
  endpoints:
    web:
      exposure:
        include: '*'

